language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    
    # The BuildTools version used by your project
    - build-tools-28.0.2
    
    # The SDK version used to compile your project
    - android-28
 
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository    
    - sys-img-armeabi-v7a-android-28

before_install:
  - yes | sdkmanager "platforms;android-28;build-tools-28.0.2;build-tools-27.0.3"

before_script:
  # Create and start emulator
  # - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  # - emulator -avd test -no-skin -no-audio -no-window &
  # - android-wait-for-emulator
  # - adb shell input keyevent 82 &

script: ./gradlew assembleRelease 
  #connectedAndroidTest
